# Generated by Django 4.1.7 on 2023-04-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner_WAVES', '0002_alter_vulnerability_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('lastname', models.CharField(default='', max_length=70)),
                ('email', models.EmailField(default='', max_length=254)),
                ('role', models.BooleanField(default=False)),
            ],
        ),
    ]
