# Generated by Django 4.1.7 on 2023-04-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner_WAVES', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnologyId', models.CharField(default='', max_length=80)),
                ('vendor', models.CharField(default='', max_length=70)),
                ('version', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=70),
        ),
    ]
