# Generated by Django 4.1.7 on 2023-04-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerabilityId', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('score', models.IntegerField(default='', max_length=4)),
                ('vulnerability_type', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
